/**
 * Aggregator for localization resources.
 * Handles the distribution of shared strings across the extension.
 * @type {Object}
 */
const BG_LOCALES = {
    en: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Customize your Gemini experience.",
        expressiveSettings: "Expressive Settings",
        headerProductivity: "Productivity",
        snippetPrefixLabel: "Snippet Prefix",
        snippetPrefixDesc: "Choose the symbol to trigger your snippets.",
        manageSnippetsLabel: "Prompt Snippets",
        manageSnippetsDesc: "Create shortcuts to auto-complete long prompts.",
        manageSnippetsBtn: "Manage",
        snippetsTitle: "Prompt Snippets",
        snippetsSubtitle: "Manage your saved prompts and quick shortcuts.",
        addSnippetBtn: "New Snippet",
        snippetKeywordLabel: "Keyword / Shortcut",
        snippetContentLabel: "Prompt Content",
        saveSnippetBtn: "Save",
        deleteSnippetBtn: "Delete",
        backToSettings: "Back to Settings",
        noSnippetsFound: "No snippets saved yet. Create one to get started!",
        snippetKeywordPlaceholder: "e.g., react",
        snippetContentPlaceholder: "Write your detailed prompt here...",
        confirmDelete: "Are you sure you want to delete this snippet?",
        createSnippetTitle: "Create New Snippet",
        editSnippetTitle: "Edit Snippet",
        createBtn: "Create",
        saveChangesBtn: "Save Changes",
        timelineLabel: "Enable Timeline Navigation",
        timelineDesc: "Adds a floating timeline on the right side to easily navigate through long conversations.",
        collapseLabel: "Enable Code Collapser",
        collapseDesc: "Allows you to collapse and expand long code blocks to save screen space.",
        headersLabel: "Enable Enhanced Code Headers",
        headersDesc: "Displays programming language icons and extracts file names for code blocks.",
        codeNavLabel: "Enable Code Block Navigation",
        codeNavDesc: "Shows floating arrows to jump between code blocks.",
        themeModeLabel: "Theme Mode",
        themeModeDesc: "Choose between light, dark, or system default appearance.",
        themeColorLabel: "Theme Color",
        themeColorDesc: "Select a seed color to generate the Material You palette.",
        dynamicColorSwitchLabel: "Enable Dynamic Color",
        dynamicColorSwitchDesc: "Applies dynamic theming to the interface.",
        headerGeneral: "General",
        headerAppearance: "Appearance",
        modeAuto: "Auto",
        modeLight: "Light",
        modeDark: "Dark",
        statusSaved: "Settings saved successfully.",
        statusSavedRefresh: "Settings saved. Please save your work and refresh the page (F5) to apply.",
        languageLabel: "Language",
        linksTitle: "Resources",
        help: "Help",
        feedback: "Feedback",
        website: "Website",
        builtBy: "Built by",
        timelineTitle: "Timeline",
        userPrompt: "You",
        geminiResponse: "Gemini",
        expandTimeline: "Expand Timeline",
        collapseTimeline: "Collapse Timeline",
        collapseCode: "Collapse",
        expandCode: "Expand",
        lang_auto: "Auto",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    pt: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Personalize sua experiência no Gemini.",
        expressiveSettings: "Configurações do Expressive",
        headerProductivity: "Produtividade",
        snippetPrefixLabel: "Prefixo do Atalho",
        snippetPrefixDesc: "Escolha o símbolo para acionar seus atalhos.",
        manageSnippetsLabel: "Atalhos de Prompts",
        manageSnippetsDesc: "Crie atalhos para preencher automaticamente prompts longos.",
        manageSnippetsBtn: "Gerenciar",
        snippetsTitle: "Atalhos de Prompts",
        snippetsSubtitle: "Gerencie seus prompts salvos e atalhos rápidos.",
        addSnippetBtn: "Novo Atalho",
        snippetKeywordLabel: "Palavra-chave / Atalho",
        snippetContentLabel: "Conteúdo do Prompt",
        saveSnippetBtn: "Salvar",
        deleteSnippetBtn: "Excluir",
        backToSettings: "Voltar para Configurações",
        noSnippetsFound: "Nenhum atalho salvo ainda.",
        snippetKeywordPlaceholder: "ex: react",
        snippetContentPlaceholder: "Escreva seu prompt detalhado aqui...",
        confirmDelete: "Tem certeza que deseja excluir este atalho?",
        createSnippetTitle: "Criar Novo Atalho",
        editSnippetTitle: "Editar Atalho",
        createBtn: "Criar",
        saveChangesBtn: "Salvar Alterações",
        timelineLabel: "Ativar Navegação por Linha do Tempo",
        timelineDesc: "Adiciona uma linha do tempo flutuante à direita para navegar facilmente por conversas longas.",
        collapseLabel: "Ativar Ocultador de Código",
        collapseDesc: "Permite ocultar e expandir blocos de código longos para economizar espaço na tela.",
        headersLabel: "Ativar Cabeçalhos de Código Aprimorados",
        headersDesc: "Exibe ícones de linguagem de programação e extrai nomes de arquivos para blocos de código.",
        codeNavLabel: "Ativar Navegação entre Códigos",
        codeNavDesc: "Exibe setas flutuantes para pular entre blocos de código.",
        themeModeLabel: "Modo de Tema",
        themeModeDesc: "Escolha entre claro, escuro ou padrão do sistema.",
        themeColorLabel: "Cor do Tema",
        themeColorDesc: "Selecione uma cor base para gerar a paleta Material You.",
        dynamicColorSwitchLabel: "Ativar Cor Dinâmica",
        dynamicColorSwitchDesc: "Aplica o tema dinâmico à interface.",
        headerGeneral: "Geral",
        headerAppearance: "Aparência",
        modeAuto: "Automático",
        modeLight: "Claro",
        modeDark: "Escuro",
        statusSaved: "Configurações salvas com sucesso.",
        statusSavedRefresh: "Configurações salvas. Por favor, salve seu trabalho e atualize a página (F5).",
        languageLabel: "Idioma",
        linksTitle: "Recursos",
        help: "Ajuda",
        feedback: "Feedback",
        website: "Site",
        builtBy: "Desenvolvido por",
        timelineTitle: "Linha do Tempo",
        userPrompt: "Você",
        geminiResponse: "Gemini",
        expandTimeline: "Expandir",
        collapseTimeline: "Recolher",
        collapseCode: "Ocultar",
        expandCode: "Expandir",
        lang_auto: "Automático",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    es: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Personaliza tu experiencia en Gemini.",
        expressiveSettings: "Configuración de Expressive",
        headerProductivity: "Productividad",
        snippetPrefixLabel: "Prefijo de Atajo",
        snippetPrefixDesc: "Elige el símbolo para activar tus atajos.",
        manageSnippetsLabel: "Atajos de Prompts",
        manageSnippetsDesc: "Crea atajos para autocompletar prompts largos.",
        manageSnippetsBtn: "Gestionar",
        snippetsTitle: "Atajos de Prompts",
        snippetsSubtitle: "Gestiona tus prompts guardados y atajos rápidos.",
        addSnippetBtn: "Nuevo Atajo",
        snippetKeywordLabel: "Palabra clave / Atajo",
        snippetContentLabel: "Contenido del Prompt",
        saveSnippetBtn: "Guardar",
        deleteSnippetBtn: "Eliminar",
        backToSettings: "Volver a Configuración",
        noSnippetsFound: "No hay atajos guardados todavía.",
        snippetKeywordPlaceholder: "ej: react",
        snippetContentPlaceholder: "Escribe tu prompt detallado aquí...",
        confirmDelete: "¿Estás seguro de que quieres eliminar este atajo?",
        createSnippetTitle: "Crear Nuevo Atajo",
        editSnippetTitle: "Editar Atajo",
        createBtn: "Crear",
        saveChangesBtn: "Guardar Cambios",
        timelineLabel: "Habilitar Navegación por Línea de Tiempo",
        timelineDesc: "Añade una línea de tiempo flotante a la derecha para navegar fácilmente por conversaciones largas.",
        collapseLabel: "Habilitar Colapsador de Código",
        collapseDesc: "Permite colapsar y expandir bloques de código largos para ahorrar espacio en la pantalla.",
        headersLabel: "Habilitar Encabezados de Código Mejorados",
        headersDesc: "Muestra iconos de lenguajes de programación y extrae nombres de archivos para bloques de código.",
        codeNavLabel: "Habilitar Navegación de Código",
        codeNavDesc: "Muestra flechas flotantes para saltar entre bloques de código.",
        themeModeLabel: "Modo de Tema",
        themeModeDesc: "Elige entre apariencia clara, oscura o predeterminada del sistema.",
        themeColorLabel: "Color del Tema",
        themeColorDesc: "Selecciona un color base para generar la paleta Material You.",
        dynamicColorSwitchLabel: "Habilitar Color Dinámico",
        dynamicColorSwitchDesc: "Aplica el tema dinámico a la interfaz.",
        headerGeneral: "General",
        headerAppearance: "Apariencia",
        modeAuto: "Automático",
        modeLight: "Claro",
        modeDark: "Oscuro",
        statusSaved: "Configuraciones guardadas con éxito.",
        statusSavedRefresh: "Configuraciones guardadas. Por favor, actualiza la página (F5) para aplicar.",
        languageLabel: "Idioma",
        linksTitle: "Recursos",
        help: "Ayuda",
        feedback: "Comentarios",
        website: "Sitio Web",
        builtBy: "Desarrollado por",
        timelineTitle: "Línea de Tiempo",
        userPrompt: "Tú",
        geminiResponse: "Gemini",
        expandTimeline: "Expandir",
        collapseTimeline: "Colapsar",
        collapseCode: "Colapsar",
        expandCode: "Expandir",
        lang_auto: "Automático",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    de: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Passen Sie Ihr Gemini-Erlebnis an.",
        expressiveSettings: "Expressive Einstellungen",
        headerProductivity: "Produktivität",
        snippetPrefixLabel: "Schnipsel-Präfix",
        snippetPrefixDesc: "Wählen Sie das Symbol zum Auslösen Ihrer Schnipsel.",
        manageSnippetsLabel: "Prompt-Schnipsel",
        manageSnippetsDesc: "Erstellen Sie Verknüpfungen zum automatischen Vervollständigen langer Prompts.",
        manageSnippetsBtn: "Verwalten",
        snippetsTitle: "Prompt-Schnipsel",
        snippetsSubtitle: "Verwalten Sie Ihre gespeicherten Prompts und schnellen Verknüpfungen.",
        addSnippetBtn: "Neuer Schnipsel",
        snippetKeywordLabel: "Schlüsselwort / Verknüpfung",
        snippetContentLabel: "Prompt-Inhalt",
        saveSnippetBtn: "Speichern",
        deleteSnippetBtn: "Löschen",
        backToSettings: "Zurück zu den Einstellungen",
        noSnippetsFound: "Noch keine Schnipsel gespeichert.",
        snippetKeywordPlaceholder: "z.B. react",
        snippetContentPlaceholder: "Schreiben Sie hier Ihren detaillierten Prompt...",
        confirmDelete: "Sind Sie sicher, dass Sie diesen Schnipsel löschen möchten?",
        createSnippetTitle: "Neuen Schnipsel erstellen",
        editSnippetTitle: "Schnipsel bearbeiten",
        createBtn: "Erstellen",
        saveChangesBtn: "Änderungen speichern",
        timelineLabel: "Timeline-Navigation aktivieren",
        timelineDesc: "Fügt eine schwebende Timeline auf der rechten Seite hinzu, um einfach durch lange Unterhaltungen zu navigieren.",
        collapseLabel: "Code-Collapser aktivieren",
        collapseDesc: "Ermöglicht das Ein- und Ausblenden von langen Codeblöcken, um Platz auf dem Bildschirm zu sparen.",
        headersLabel: "Erweiterte Code-Header aktivieren",
        headersDesc: "Zeigt Programmiersprachensymbole an und extrahiert Dateinamen für Codeblöcke.",
        codeNavLabel: "Code-Navigation aktivieren",
        codeNavDesc: "Zeigt schwebende Pfeile an, um zwischen Codeblöcken zu springen.",
        themeModeLabel: "Theme-Modus",
        themeModeDesc: "Wählen Sie zwischen hellem, dunklem oder Systemstandard-Design.",
        themeColorLabel: "Theme-Farbe",
        themeColorDesc: "Wählen Sie eine Grundfarbe, um die Material You-Palette zu generieren.",
        dynamicColorSwitchLabel: "Dynamische Farbe aktivieren",
        dynamicColorSwitchDesc: "Wendet das dynamische Design auf die Benutzeroberfläche an.",
        headerGeneral: "Allgemein",
        headerAppearance: "Erscheinungsbild",
        modeAuto: "Automatisch",
        modeLight: "Hell",
        modeDark: "Dunkel",
        statusSaved: "Einstellungen erfolgreich gespeichert.",
        statusSavedRefresh: "Einstellungen gespeichert. Bitte aktualisieren Sie die Seite (F5).",
        languageLabel: "Sprache",
        linksTitle: "Ressourcen",
        help: "Hilfe",
        feedback: "Feedback",
        website: "Webseite",
        builtBy: "Entwickelt von",
        timelineTitle: "Zeitleiste",
        userPrompt: "Du",
        geminiResponse: "Gemini",
        expandTimeline: "Erweitern",
        collapseTimeline: "Zusammenklappen",
        collapseCode: "Zusammenklappen",
        expandCode: "Erweitern",
        lang_auto: "Automatisch",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    hi: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "अपने Gemini अनुभव को अनुकूलित करें।",
        expressiveSettings: "Expressive सेटिंग्स",
        headerProductivity: "उत्पादकता",
        snippetPrefixLabel: "स्निपेट उपसर्ग",
        snippetPrefixDesc: "अपने स्निपेट ट्रिगर करने के लिए प्रतीक चुनें।",
        manageSnippetsLabel: "प्रॉम्प्ट स्निपेट्स",
        manageSnippetsDesc: "लंबे प्रॉम्प्ट को स्वतः पूर्ण करने के लिए शॉर्टकट बनाएं।",
        manageSnippetsBtn: "प्रबंधित करें",
        snippetsTitle: "प्रॉम्प्ट स्निपेट्स",
        snippetsSubtitle: "अपने सहेजे गए प्रॉम्प्ट और त्वरित शॉर्टकट प्रबंधित करें।",
        addSnippetBtn: "नया स्निपेट",
        snippetKeywordLabel: "कीवर्ड / शॉर्टकट",
        snippetContentLabel: "प्रॉम्प्ट सामग्री",
        saveSnippetBtn: "सहेजें",
        deleteSnippetBtn: "हटाएं",
        backToSettings: "सेटिंग्स पर वापस जाएं",
        noSnippetsFound: "अभी तक कोई स्निपेट सहेजा नहीं गया है।",
        snippetKeywordPlaceholder: "उदा., react",
        snippetContentPlaceholder: "अपना विस्तृत प्रॉम्प्ट यहां लिखें...",
        confirmDelete: "क्या आप वाकई इस स्निपेट को हटाना चाहते हैं?",
        createSnippetTitle: "नया स्निपेट बनाएं",
        editSnippetTitle: "स्निपेट संपादित करें",
        createBtn: "बनाएं",
        saveChangesBtn: "परिवर्तन सहेजें",
        timelineLabel: "टाइमलाइन नेविगेशन सक्षम करें",
        timelineDesc: "लंबी बातचीत के माध्यम से आसानी से नेविगेट करने के लिए दाईं ओर एक फ्लोटिंग टाइमलाइन जोड़ता है।",
        collapseLabel: "कोड कोलैप्सर सक्षम करें",
        collapseDesc: "स्क्रीन स्पेस बचाने के लिए आपको लंबे कोड ब्लॉक को संक्षिप्त और विस्तारित करने की अनुमति देता है।",
        headersLabel: "उन्नत कोड हेडर सक्षम करें",
        headersDesc: "प्रोग्रामिंग भाषा आइकन प्रदर्शित करता है और कोड ब्लॉक के लिए फ़ाइल नाम निकालता है।",
        codeNavLabel: "कोड नेविगेशन सक्षम करें",
        codeNavDesc: "कोड ब्लॉक के बीच कूदने के लिए फ़्लोटिंग तीर दिखाता है।",
        themeModeLabel: "थीम मोड",
        themeModeDesc: "हल्के, गहरे या सिस्टम डिफ़ॉल्ट उपस्थिति में से चुनें।",
        themeColorLabel: "थीम का रंग",
        themeColorDesc: "Material You पैलेट उत्पन्न करने के लिए एक मूल रंग चुनें।",
        dynamicColorSwitchLabel: "डायनामिक रंग सक्षम करें",
        dynamicColorSwitchDesc: "इंटरफ़ेस पर डायनामिक थीम लागू करता है।",
        headerGeneral: "सामान्य",
        headerAppearance: "दिखावट",
        modeAuto: "स्वचालित",
        modeLight: "रोशनी",
        modeDark: "अंधेरा",
        statusSaved: "सेटिंग्स सफलतापूर्वक सहेजी गईं।",
        statusSavedRefresh: "सेटिंग्स सहेजी गईं। कृपया पृष्ठ को रीफ्रेश करें (F5)।",
        languageLabel: "भाषा",
        linksTitle: "संसाधन",
        help: "सहायता",
        feedback: "प्रतिक्रिया",
        website: "वेबसाइट",
        builtBy: "द्वारा निर्मित",
        timelineTitle: "टाइमलाइन",
        userPrompt: "आप",
        geminiResponse: "Gemini",
        expandTimeline: "विस्तार करें",
        collapseTimeline: "संक्षिप्त करें",
        collapseCode: "संक्षिप्त करें",
        expandCode: "विस्तार करें",
        lang_auto: "स्वचालित",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    ja: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Geminiのエクスペリエンスをカスタマイズします。",
        expressiveSettings: "Expressive 設定",
        headerProductivity: "生産性",
        snippetPrefixLabel: "スニペットプレフィックス",
        snippetPrefixDesc: "スニペットをトリガーする記号を選択します。",
        manageSnippetsLabel: "プロンプトスニペット",
        manageSnippetsDesc: "長いプロンプトを自動補完するショートカットを作成します。",
        manageSnippetsBtn: "管理",
        snippetsTitle: "プロンプトスニペット",
        snippetsSubtitle: "保存されたプロンプトとクイックショートカットを管理します。",
        addSnippetBtn: "新しいスニペット",
        snippetKeywordLabel: "キーワード / ショートカット",
        snippetContentLabel: "プロンプトの内容",
        saveSnippetBtn: "保存",
        deleteSnippetBtn: "削除",
        backToSettings: "設定に戻る",
        noSnippetsFound: "スニペットはまだ保存されていません。",
        snippetKeywordPlaceholder: "例: react",
        snippetContentPlaceholder: "ここに詳細なプロンプトを記述します...",
        confirmDelete: "このスニペットを削除してもよろしいですか？",
        createSnippetTitle: "新しいスニペットを作成",
        editSnippetTitle: "スニペットを編集",
        createBtn: "作成",
        saveChangesBtn: "変更を保存",
        timelineLabel: "タイムラインナビゲーションを有効にする",
        timelineDesc: "長い会話を簡単にナビゲートするために、右側にフローティングタイムラインを追加します。",
        collapseLabel: "コードコラプサーを有効にする",
        collapseDesc: "画面スペースを節約するために、長いコードブロックを折りたたんだり展開したりできます。",
        headersLabel: "拡張コードヘッダーを有効にする",
        headersDesc: "プログラミング言語のアイコンを表示し、コードブロックのファイル名を抽出します。",
        codeNavLabel: "コードナビゲーションを有効にする",
        codeNavDesc: "コードブロック間をジャンプするためのフローティング矢印を表示します。",
        themeModeLabel: "テーマモード",
        themeModeDesc: "ライト、ダーク、またはシステムのデフォルトの外観から選択します。",
        themeColorLabel: "テーマカラー",
        themeColorDesc: "Material Youパレットを生成するためのシードカラーを選択します。",
        dynamicColorSwitchLabel: "ダイナミックカラーを有効にする",
        dynamicColorSwitchDesc: "インターフェースにダイナミックテーマを適用します。",
        headerGeneral: "一般",
        headerAppearance: "外観",
        modeAuto: "自動",
        modeLight: "ライト",
        modeDark: "ダーク",
        statusSaved: "設定が正常に保存されました。",
        statusSavedRefresh: "設定が保存されました。F5キーを押して適用してください。",
        languageLabel: "言語",
        linksTitle: "リソース",
        help: "ヘルプ",
        feedback: "フィードバック",
        website: "ウェブサイト",
        builtBy: "開発者",
        timelineTitle: "タイムライン",
        userPrompt: "あなた",
        geminiResponse: "Gemini",
        expandTimeline: "展開",
        collapseTimeline: "折りたたむ",
        collapseCode: "折りたたむ",
        expandCode: "展開",
        lang_auto: "自動",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    }
};

/**
 * Current active language state.
 * @type {string}
 */
let currentLanguage = 'en';

/**
 * Initializes the language based on browser settings, subsequently overridden by user preference.
 */
function initLanguage() {
    try {
        const browserLang = navigator.language.split('-')[0];
        if (BG_LOCALES[browserLang]) {
            currentLanguage = browserLang;
        }

        if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.sync) {
            chrome.storage.sync.get(['language'], (items) => {
                if (items.language && items.language !== 'auto' && BG_LOCALES[items.language]) {
                    currentLanguage = items.language;
                }
            });
        }
    } catch (e) {
    }
}

initLanguage();

/**
 * Retrieves the localized string for a given key.
 * @param {string} key The translation key.
 * @returns {string} The localized string.
 */
function getBgString(key) {
    return BG_LOCALES[currentLanguage][key] || BG_LOCALES['en'][key] || key;
}