/**
 * Aggregator for localization resources.
 * Handles the distribution of shared strings across the extension.
 * @type {Object}
 */
const BG_LOCALES = {
    en: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Customize your Gemini experience.",
        timelineLabel: "Enable Timeline Navigation",
        timelineDesc: "Adds a floating timeline on the right side to easily navigate through long conversations.",
        collapseLabel: "Enable Code Collapser",
        collapseDesc: "Allows you to collapse and expand long code blocks to save screen space.",
        headersLabel: "Enable Enhanced Code Headers",
        headersDesc: "Displays programming language icons and extracts file names for code blocks.",
        codeNavLabel: "Enable Code Block Navigation",
        codeNavDesc: "Shows floating arrows to jump between code blocks.",
        themeModeLabel: "Theme Mode",
        themeModeDesc: "Choose between light, dark, or system default appearance.",
        themeColorLabel: "Dynamic Color",
        themeColorDesc: "Select a seed color to generate the Material You palette.",
        modeAuto: "Auto",
        modeLight: "Light",
        modeDark: "Dark",
        statusSaved: "Settings saved successfully.",
        languageLabel: "Language",
        linksTitle: "Resources",
        help: "Help",
        feedback: "Feedback",
        website: "Website",
        builtBy: "Built by",
        timelineTitle: "Timeline",
        userPrompt: "You",
        geminiResponse: "Gemini",
        expandTimeline: "Expand Timeline",
        collapseTimeline: "Collapse Timeline",
        collapseCode: "Collapse",
        expandCode: "Expand",
        lang_auto: "Auto",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    pt: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Personalize sua experiência no Gemini.",
        timelineLabel: "Ativar Navegação por Linha do Tempo",
        timelineDesc: "Adiciona uma linha do tempo flutuante à direita para navegar facilmente por conversas longas.",
        collapseLabel: "Ativar Ocultador de Código",
        collapseDesc: "Permite ocultar e expandir blocos de código longos para economizar espaço na tela.",
        headersLabel: "Ativar Cabeçalhos de Código Aprimorados",
        headersDesc: "Exibe ícones de linguagem de programação e extrai nomes de arquivos para blocos de código.",
        codeNavLabel: "Ativar Navegação entre Códigos",
        codeNavDesc: "Exibe setas flutuantes para pular entre blocos de código.",
        themeModeLabel: "Modo de Tema",
        themeModeDesc: "Escolha entre claro, escuro ou padrão do sistema.",
        themeColorLabel: "Cor Dinâmica",
        themeColorDesc: "Selecione uma cor base para gerar a paleta Material You.",
        modeAuto: "Automático",
        modeLight: "Claro",
        modeDark: "Escuro",
        statusSaved: "Configurações salvas com sucesso.",
        languageLabel: "Idioma",
        linksTitle: "Recursos",
        help: "Ajuda",
        feedback: "Feedback",
        website: "Site",
        builtBy: "Desenvolvido por",
        timelineTitle: "Linha do Tempo",
        userPrompt: "Você",
        geminiResponse: "Gemini",
        expandTimeline: "Expandir",
        collapseTimeline: "Recolher",
        collapseCode: "Ocultar",
        expandCode: "Expandir",
        lang_auto: "Automático",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    es: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Personaliza tu experiencia en Gemini.",
        timelineLabel: "Habilitar Navegación por Línea de Tiempo",
        timelineDesc: "Añade una línea de tiempo flotante a la derecha para navegar fácilmente por conversaciones largas.",
        collapseLabel: "Habilitar Colapsador de Código",
        collapseDesc: "Permite colapsar y expandir bloques de código largos para ahorrar espacio en la pantalla.",
        headersLabel: "Habilitar Encabezados de Código Mejorados",
        headersDesc: "Muestra iconos de lenguajes de programación y extrae nombres de archivos para bloques de código.",
        codeNavLabel: "Habilitar Navegación de Código",
        codeNavDesc: "Muestra flechas flotantes para saltar entre bloques de código.",
        themeModeLabel: "Modo de Tema",
        themeModeDesc: "Elige entre apariencia clara, oscura o predeterminada del sistema.",
        themeColorLabel: "Color Dinámico",
        themeColorDesc: "Selecciona un color base para generar la paleta Material You.",
        modeAuto: "Automático",
        modeLight: "Claro",
        modeDark: "Oscuro",
        statusSaved: "Configuraciones guardadas con éxito.",
        languageLabel: "Idioma",
        linksTitle: "Recursos",
        help: "Ayuda",
        feedback: "Comentarios",
        website: "Sitio Web",
        builtBy: "Desarrollado por",
        timelineTitle: "Línea de Tiempo",
        userPrompt: "Tú",
        geminiResponse: "Gemini",
        expandTimeline: "Expandir",
        collapseTimeline: "Colapsar",
        collapseCode: "Colapsar",
        expandCode: "Expandir",
        lang_auto: "Automático",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    de: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Passen Sie Ihr Gemini-Erlebnis an.",
        timelineLabel: "Timeline-Navigation aktivieren",
        timelineDesc: "Fügt eine schwebende Timeline auf der rechten Seite hinzu, um einfach durch lange Unterhaltungen zu navigieren.",
        collapseLabel: "Code-Collapser aktivieren",
        collapseDesc: "Ermöglicht das Ein- und Ausblenden von langen Codeblöcken, um Platz auf dem Bildschirm zu sparen.",
        headersLabel: "Erweiterte Code-Header aktivieren",
        headersDesc: "Zeigt Programmiersprachensymbole an und extrahiert Dateinamen für Codeblöcke.",
        codeNavLabel: "Code-Navigation aktivieren",
        codeNavDesc: "Zeigt schwebende Pfeile an, um zwischen Codeblöcken zu springen.",
        themeModeLabel: "Theme-Modus",
        themeModeDesc: "Wählen Sie zwischen hellem, dunklem oder Systemstandard-Design.",
        themeColorLabel: "Dynamische Farbe",
        themeColorDesc: "Wählen Sie eine Grundfarbe, um die Material You-Palette zu generieren.",
        modeAuto: "Automatisch",
        modeLight: "Hell",
        modeDark: "Dunkel",
        statusSaved: "Einstellungen erfolgreich gespeichert.",
        languageLabel: "Sprache",
        linksTitle: "Ressourcen",
        help: "Hilfe",
        feedback: "Feedback",
        website: "Webseite",
        builtBy: "Entwickelt von",
        timelineTitle: "Zeitleiste",
        userPrompt: "Du",
        geminiResponse: "Gemini",
        expandTimeline: "Erweitern",
        collapseTimeline: "Zusammenklappen",
        collapseCode: "Zusammenklappen",
        expandCode: "Erweitern",
        lang_auto: "Automatisch",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    hi: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "अपने Gemini अनुभव को अनुकूलित करें।",
        timelineLabel: "टाइमलाइन नेविगेशन सक्षम करें",
        timelineDesc: "लंबी बातचीत के माध्यम से आसानी से नेविगेट करने के लिए दाईं ओर एक फ्लोटिंग टाइमलाइन जोड़ता है।",
        collapseLabel: "कोड कोलैप्सर सक्षम करें",
        collapseDesc: "स्क्रीन स्पेस बचाने के लिए आपको लंबे कोड ब्लॉक को संक्षिप्त और विस्तारित करने की अनुमति देता है।",
        headersLabel: "उन्नत कोड हेडर सक्षम करें",
        headersDesc: "प्रोग्रामिंग भाषा आइकन प्रदर्शित करता है और कोड ब्लॉक के लिए फ़ाइल नाम निकालता है।",
        codeNavLabel: "कोड नेविगेशन सक्षम करें",
        codeNavDesc: "कोड ब्लॉक के बीच कूदने के लिए फ़्लोटिंग तीर दिखाता है।",
        themeModeLabel: "थीम मोड",
        themeModeDesc: "हल्के, गहरे या सिस्टम डिफ़ॉल्ट उपस्थिति में से चुनें।",
        themeColorLabel: "गतिशील रंग",
        themeColorDesc: "Material You पैलेट उत्पन्न करने के लिए एक मूल रंग चुनें।",
        modeAuto: "स्वचालित",
        modeLight: "रोशनी",
        modeDark: "अंधेरा",
        statusSaved: "सेटिंग्स सफलतापूर्वक सहेजी गईं।",
        languageLabel: "भाषा",
        linksTitle: "संसाधन",
        help: "सहायता",
        feedback: "प्रतिक्रिया",
        website: "वेबसाइट",
        builtBy: "द्वारा निर्मित",
        timelineTitle: "टाइमलाइन",
        userPrompt: "आप",
        geminiResponse: "Gemini",
        expandTimeline: "विस्तार करें",
        collapseTimeline: "संक्षिप्त करें",
        collapseCode: "संक्षिप्त करें",
        expandCode: "विस्तार करें",
        lang_auto: "स्वचालित",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    },
    ja: {
        settingsTitle: "Gemini Expressive",
        settingsSubtitle: "Geminiのエクスペリエンスをカスタマイズします。",
        timelineLabel: "タイムラインナビゲーションを有効にする",
        timelineDesc: "長い会話を簡単にナビゲートするために、右側にフローティングタイムラインを追加します。",
        collapseLabel: "コードコラプサーを有効にする",
        collapseDesc: "画面スペースを節約するために、長いコードブロックを折りたたんだり展開したりできます。",
        headersLabel: "拡張コードヘッダーを有効にする",
        headersDesc: "プログラミング言語のアイコンを表示し、コードブロックのファイル名を抽出します。",
        codeNavLabel: "コードナビゲーションを有効にする",
        codeNavDesc: "コードブロック間をジャンプするためのフローティング矢印を表示します。",
        themeModeLabel: "テーマモード",
        themeModeDesc: "ライト、ダーク、またはシステムのデフォルトの外観から選択します。",
        themeColorLabel: "ダイナミックカラー",
        themeColorDesc: "Material Youパレットを生成するためのシードカラーを選択します。",
        modeAuto: "自動",
        modeLight: "ライト",
        modeDark: "ダーク",
        statusSaved: "設定が正常に保存されました。",
        languageLabel: "言語",
        linksTitle: "リソース",
        help: "ヘルプ",
        feedback: "フィードバック",
        website: "ウェブサイト",
        builtBy: "開発者",
        timelineTitle: "タイムライン",
        userPrompt: "あなた",
        geminiResponse: "Gemini",
        expandTimeline: "展開",
        collapseTimeline: "折りたたむ",
        collapseCode: "折りたたむ",
        expandCode: "展開",
        lang_auto: "自動",
        lang_en: "English",
        lang_pt: "Português",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_hi: "हिन्दी",
        lang_ja: "日本語",
        colorBlue: "Blue",
        colorGray: "Gray",
        colorIndigo: "Indigo",
        colorBlueGray: "Blue Gray",
        colorTealGray: "Teal Gray",
        colorTeal: "Teal",
        colorGreen: "Green",
        colorOliveGray: "Olive Gray",
        colorYellow: "Yellow",
        colorOrange: "Orange",
        colorBrown: "Brown",
        colorRose: "Rose",
        colorMauve: "Mauve",
        colorPinkPurple: "Pink Purple",
        colorPurple: "Purple",
        colorCustom: "Custom Color"
    }
};

/**
 * Current active language state.
 * @type {string}
 */
let currentLanguage = 'en';

/**
 * Initializes the language based on browser settings, subsequently overridden by user preference.
 */
function initLanguage() {
    try {
        const browserLang = navigator.language.split('-')[0];
        if (BG_LOCALES[browserLang]) {
            currentLanguage = browserLang;
        }

        if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.sync) {
            chrome.storage.sync.get(['language'], (items) => {
                if (items.language && items.language !== 'auto' && BG_LOCALES[items.language]) {
                    currentLanguage = items.language;
                }
            });
        }
    } catch (e) {
    }
}

initLanguage();

/**
 * Retrieves the localized string for a given key.
 * @param {string} key The translation key.
 * @returns {string} The localized string.
 */
function getBgString(key) {
    return BG_LOCALES[currentLanguage][key] || BG_LOCALES['en'][key] || key;
}